using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [humanresources].[employeedepartmenthistory] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:27 PM
// This is only meant to be indicative of the features available in the core product.

public class HumanresourcesEmployeedepartmenthistory : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public int Departmentid { get; set; }
    public int Shiftid { get; set; }
    public DateTime Startdate { get; set; }
    public DateTime? Enddate { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class HumanresourcesEmployeedepartmenthistoryRowsData : BaseTableRowsData
{
    public List<HumanresourcesEmployeedepartmenthistory> Rows { get; set; } = new();
}

public class HumanresourcesEmployeedepartmenthistoryInsertedData : BaseTableInsertedData
{
    public HumanresourcesEmployeedepartmenthistory? InsertedRow { get; set; }
}

public class HumanresourcesEmployeedepartmenthistoryRowData : BaseTableRowData
{
    public HumanresourcesEmployeedepartmenthistory? Row { get; set; }
}

public class HumanresourcesEmployeedepartmenthistoryDataSource : BasePostgresTableDataSource<HumanresourcesEmployeedepartmenthistory>
{
    public HumanresourcesEmployeedepartmenthistoryDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("humanresources");
        _encTable = RedflyEncryption.EncryptToString("employeedepartmenthistory");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, int departmentid, int shiftid, DateTime startdate, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("departmentid", departmentid.ToString());
        req.PrimaryKeyValues.Add("shiftid", shiftid.ToString());
        req.PrimaryKeyValues.Add("startdate", startdate.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<HumanresourcesEmployeedepartmenthistoryRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<HumanresourcesEmployeedepartmenthistory>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new HumanresourcesEmployeedepartmenthistoryRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<HumanresourcesEmployeedepartmenthistoryInsertedData> InsertAsync(HumanresourcesEmployeedepartmenthistory entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new HumanresourcesEmployeedepartmenthistoryInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<HumanresourcesEmployeedepartmenthistoryRowData> GetAsync(int businessentityid, int departmentid, int shiftid, DateTime startdate, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("departmentid", departmentid.ToString());
        req.PrimaryKeyValues.Add("shiftid", shiftid.ToString());
        req.PrimaryKeyValues.Add("startdate", startdate.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new HumanresourcesEmployeedepartmenthistoryRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(HumanresourcesEmployeedepartmenthistory entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override HumanresourcesEmployeedepartmenthistory MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new HumanresourcesEmployeedepartmenthistory
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Departmentid = dict.TryGetValue("departmentid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Shiftid = dict.TryGetValue("shiftid", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : default(int),
            Startdate = dict.TryGetValue("startdate", out var v4) && !string.IsNullOrEmpty(v4) ? (DateTime)Convert.ChangeType(v4, typeof(DateTime)) : default(DateTime),
            Enddate = dict.TryGetValue("enddate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : null,
            Modifieddate = dict.TryGetValue("modifieddate", out var v6) && !string.IsNullOrEmpty(v6) ? (DateTime)Convert.ChangeType(v6, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(HumanresourcesEmployeedepartmenthistory entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "departmentid", Value = new Value { StringValue = entity.Departmentid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "shiftid", Value = new Value { StringValue = entity.Shiftid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "startdate", Value = new Value { StringValue = entity.Startdate.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Enddate != null)
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = entity.Enddate.Value.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = null } });
        }
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
