using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [humanresources].[department] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:18 PM
// This is only meant to be indicative of the features available in the core product.

public class HumanresourcesDepartment : BasePostgresTableSchema
{
    public int Departmentid { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Groupname { get; set; } = string.Empty;
    public DateTime Modifieddate { get; set; }
}

public class HumanresourcesDepartmentRowsData : BaseTableRowsData
{
    public List<HumanresourcesDepartment> Rows { get; set; } = new();
}

public class HumanresourcesDepartmentInsertedData : BaseTableInsertedData
{
    public HumanresourcesDepartment? InsertedRow { get; set; }
}

public class HumanresourcesDepartmentRowData : BaseTableRowData
{
    public HumanresourcesDepartment? Row { get; set; }
}

public class HumanresourcesDepartmentDataSource : BasePostgresTableDataSource<HumanresourcesDepartment>
{
    public HumanresourcesDepartmentDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("humanresources");
        _encTable = RedflyEncryption.EncryptToString("department");
    }

    public async Task<DeletedData> DeleteAsync(int departmentid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("departmentid", departmentid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<HumanresourcesDepartmentRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<HumanresourcesDepartment>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new HumanresourcesDepartmentRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<HumanresourcesDepartmentInsertedData> InsertAsync(HumanresourcesDepartment entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new HumanresourcesDepartmentInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<HumanresourcesDepartmentRowData> GetAsync(int departmentid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("departmentid", departmentid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new HumanresourcesDepartmentRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(HumanresourcesDepartment entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override HumanresourcesDepartment MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new HumanresourcesDepartment
        {
            Departmentid = dict.TryGetValue("departmentid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Name = dict.TryGetValue("name", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Groupname = dict.TryGetValue("groupname", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Modifieddate = dict.TryGetValue("modifieddate", out var v4) && !string.IsNullOrEmpty(v4) ? (DateTime)Convert.ChangeType(v4, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(HumanresourcesDepartment entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "departmentid", Value = new Value { StringValue = entity.Departmentid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "groupname", Value = new Value { StringValue = entity.Groupname } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
