using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [person].[businessentity] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class PersonBusinessentity : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class PersonBusinessentityRowsData : BaseTableRowsData
{
    public List<PersonBusinessentity> Rows { get; set; } = new();
}

public class PersonBusinessentityInsertedData : BaseTableInsertedData
{
    public PersonBusinessentity? InsertedRow { get; set; }
}

public class PersonBusinessentityRowData : BaseTableRowData
{
    public PersonBusinessentity? Row { get; set; }
}

public class PersonBusinessentityDataSource : BasePostgresTableDataSource<PersonBusinessentity>
{
    public PersonBusinessentityDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("person");
        _encTable = RedflyEncryption.EncryptToString("businessentity");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PersonBusinessentityRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PersonBusinessentity>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PersonBusinessentityRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PersonBusinessentityInsertedData> InsertAsync(PersonBusinessentity entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PersonBusinessentityInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PersonBusinessentityRowData> GetAsync(int businessentityid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PersonBusinessentityRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PersonBusinessentity entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PersonBusinessentity MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PersonBusinessentity
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Rowguid = dict.TryGetValue("rowguid", out var v2) && !string.IsNullOrEmpty(v2) ? (Guid)Convert.ChangeType(v2, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v3) && !string.IsNullOrEmpty(v3) ? (DateTime)Convert.ChangeType(v3, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PersonBusinessentity entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
