using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [person].[businessentityaddress] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class PersonBusinessentityaddress : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public int Addressid { get; set; }
    public int Addresstypeid { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class PersonBusinessentityaddressRowsData : BaseTableRowsData
{
    public List<PersonBusinessentityaddress> Rows { get; set; } = new();
}

public class PersonBusinessentityaddressInsertedData : BaseTableInsertedData
{
    public PersonBusinessentityaddress? InsertedRow { get; set; }
}

public class PersonBusinessentityaddressRowData : BaseTableRowData
{
    public PersonBusinessentityaddress? Row { get; set; }
}

public class PersonBusinessentityaddressDataSource : BasePostgresTableDataSource<PersonBusinessentityaddress>
{
    public PersonBusinessentityaddressDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("person");
        _encTable = RedflyEncryption.EncryptToString("businessentityaddress");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, int addressid, int addresstypeid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("addressid", addressid.ToString());
        req.PrimaryKeyValues.Add("addresstypeid", addresstypeid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PersonBusinessentityaddressRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PersonBusinessentityaddress>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PersonBusinessentityaddressRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PersonBusinessentityaddressInsertedData> InsertAsync(PersonBusinessentityaddress entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PersonBusinessentityaddressInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PersonBusinessentityaddressRowData> GetAsync(int businessentityid, int addressid, int addresstypeid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("addressid", addressid.ToString());
        req.PrimaryKeyValues.Add("addresstypeid", addresstypeid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PersonBusinessentityaddressRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PersonBusinessentityaddress entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PersonBusinessentityaddress MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PersonBusinessentityaddress
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Addressid = dict.TryGetValue("addressid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Addresstypeid = dict.TryGetValue("addresstypeid", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : default(int),
            Rowguid = dict.TryGetValue("rowguid", out var v4) && !string.IsNullOrEmpty(v4) ? (Guid)Convert.ChangeType(v4, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PersonBusinessentityaddress entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "addressid", Value = new Value { StringValue = entity.Addressid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "addresstypeid", Value = new Value { StringValue = entity.Addresstypeid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
