using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [person].[phonenumbertype] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class PersonPhonenumbertype : BasePostgresTableSchema
{
    public int Phonenumbertypeid { get; set; }
    public string Name { get; set; } = string.Empty;
    public DateTime Modifieddate { get; set; }
}

public class PersonPhonenumbertypeRowsData : BaseTableRowsData
{
    public List<PersonPhonenumbertype> Rows { get; set; } = new();
}

public class PersonPhonenumbertypeInsertedData : BaseTableInsertedData
{
    public PersonPhonenumbertype? InsertedRow { get; set; }
}

public class PersonPhonenumbertypeRowData : BaseTableRowData
{
    public PersonPhonenumbertype? Row { get; set; }
}

public class PersonPhonenumbertypeDataSource : BasePostgresTableDataSource<PersonPhonenumbertype>
{
    public PersonPhonenumbertypeDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("person");
        _encTable = RedflyEncryption.EncryptToString("phonenumbertype");
    }

    public async Task<DeletedData> DeleteAsync(int phonenumbertypeid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("phonenumbertypeid", phonenumbertypeid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PersonPhonenumbertypeRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PersonPhonenumbertype>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PersonPhonenumbertypeRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PersonPhonenumbertypeInsertedData> InsertAsync(PersonPhonenumbertype entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PersonPhonenumbertypeInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PersonPhonenumbertypeRowData> GetAsync(int phonenumbertypeid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("phonenumbertypeid", phonenumbertypeid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PersonPhonenumbertypeRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PersonPhonenumbertype entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PersonPhonenumbertype MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PersonPhonenumbertype
        {
            Phonenumbertypeid = dict.TryGetValue("phonenumbertypeid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Name = dict.TryGetValue("name", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Modifieddate = dict.TryGetValue("modifieddate", out var v3) && !string.IsNullOrEmpty(v3) ? (DateTime)Convert.ChangeType(v3, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PersonPhonenumbertype entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "phonenumbertypeid", Value = new Value { StringValue = entity.Phonenumbertypeid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
