using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [person].[stateprovince] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:26 PM
// This is only meant to be indicative of the features available in the core product.

public class PersonStateprovince : BasePostgresTableSchema
{
    public int Stateprovinceid { get; set; }
    public string Stateprovincecode { get; set; } = string.Empty;
    public string Countryregioncode { get; set; } = string.Empty;
    public bool Isonlystateprovinceflag { get; set; }
    public string Name { get; set; } = string.Empty;
    public int Territoryid { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class PersonStateprovinceRowsData : BaseTableRowsData
{
    public List<PersonStateprovince> Rows { get; set; } = new();
}

public class PersonStateprovinceInsertedData : BaseTableInsertedData
{
    public PersonStateprovince? InsertedRow { get; set; }
}

public class PersonStateprovinceRowData : BaseTableRowData
{
    public PersonStateprovince? Row { get; set; }
}

public class PersonStateprovinceDataSource : BasePostgresTableDataSource<PersonStateprovince>
{
    public PersonStateprovinceDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("person");
        _encTable = RedflyEncryption.EncryptToString("stateprovince");
    }

    public async Task<DeletedData> DeleteAsync(int stateprovinceid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("stateprovinceid", stateprovinceid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PersonStateprovinceRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PersonStateprovince>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PersonStateprovinceRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PersonStateprovinceInsertedData> InsertAsync(PersonStateprovince entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PersonStateprovinceInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PersonStateprovinceRowData> GetAsync(int stateprovinceid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("stateprovinceid", stateprovinceid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PersonStateprovinceRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PersonStateprovince entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PersonStateprovince MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PersonStateprovince
        {
            Stateprovinceid = dict.TryGetValue("stateprovinceid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Stateprovincecode = dict.TryGetValue("stateprovincecode", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Countryregioncode = dict.TryGetValue("countryregioncode", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Isonlystateprovinceflag = dict.TryGetValue("isonlystateprovinceflag", out var v4) && !string.IsNullOrEmpty(v4) ? (bool)Convert.ChangeType(v4, typeof(bool)) : default(bool),
            Name = dict.TryGetValue("name", out var v5) && !string.IsNullOrEmpty(v5) ? (string)Convert.ChangeType(v5, typeof(string)) : default(string),
            Territoryid = dict.TryGetValue("territoryid", out var v6) && !string.IsNullOrEmpty(v6) ? (int)Convert.ChangeType(v6, typeof(int)) : default(int),
            Rowguid = dict.TryGetValue("rowguid", out var v7) && !string.IsNullOrEmpty(v7) ? (Guid)Convert.ChangeType(v7, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v8) && !string.IsNullOrEmpty(v8) ? (DateTime)Convert.ChangeType(v8, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PersonStateprovince entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "stateprovinceid", Value = new Value { StringValue = entity.Stateprovinceid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "stateprovincecode", Value = new Value { StringValue = entity.Stateprovincecode } });
        row.Entries.Add(new RowEntry { Column = "countryregioncode", Value = new Value { StringValue = entity.Countryregioncode } });
        row.Entries.Add(new RowEntry { Column = "isonlystateprovinceflag", Value = new Value { StringValue = entity.Isonlystateprovinceflag.ToString() } });
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = entity.Territoryid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
