using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [person].[address] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:17 PM
// This is only meant to be indicative of the features available in the core product.

public class PersonAddress : BasePostgresTableSchema
{
    public int Addressid { get; set; }
    public string Addressline1 { get; set; } = string.Empty;
    public string? Addressline2 { get; set; }
    public string City { get; set; } = string.Empty;
    public int Stateprovinceid { get; set; }
    public string Postalcode { get; set; } = string.Empty;
    public string? Spatiallocation { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class PersonAddressRowsData : BaseTableRowsData
{
    public List<PersonAddress> Rows { get; set; } = new();
}

public class PersonAddressInsertedData : BaseTableInsertedData
{
    public PersonAddress? InsertedRow { get; set; }
}

public class PersonAddressRowData : BaseTableRowData
{
    public PersonAddress? Row { get; set; }
}

public class PersonAddressDataSource : BasePostgresTableDataSource<PersonAddress>
{
    public PersonAddressDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("person");
        _encTable = RedflyEncryption.EncryptToString("address");
    }

    public async Task<DeletedData> DeleteAsync(int addressid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("addressid", addressid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PersonAddressRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PersonAddress>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PersonAddressRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PersonAddressInsertedData> InsertAsync(PersonAddress entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PersonAddressInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PersonAddressRowData> GetAsync(int addressid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("addressid", addressid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PersonAddressRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PersonAddress entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PersonAddress MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PersonAddress
        {
            Addressid = dict.TryGetValue("addressid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Addressline1 = dict.TryGetValue("addressline1", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Addressline2 = dict.TryGetValue("addressline2", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : null,
            City = dict.TryGetValue("city", out var v4) && !string.IsNullOrEmpty(v4) ? (string)Convert.ChangeType(v4, typeof(string)) : default(string),
            Stateprovinceid = dict.TryGetValue("stateprovinceid", out var v5) && !string.IsNullOrEmpty(v5) ? (int)Convert.ChangeType(v5, typeof(int)) : default(int),
            Postalcode = dict.TryGetValue("postalcode", out var v6) && !string.IsNullOrEmpty(v6) ? (string)Convert.ChangeType(v6, typeof(string)) : default(string),
            Spatiallocation = dict.TryGetValue("spatiallocation", out var v7) && !string.IsNullOrEmpty(v7) ? (string)Convert.ChangeType(v7, typeof(string)) : null,
            Rowguid = dict.TryGetValue("rowguid", out var v8) && !string.IsNullOrEmpty(v8) ? (Guid)Convert.ChangeType(v8, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v9) && !string.IsNullOrEmpty(v9) ? (DateTime)Convert.ChangeType(v9, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PersonAddress entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "addressid", Value = new Value { StringValue = entity.Addressid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "addressline1", Value = new Value { StringValue = entity.Addressline1 } });
        row.Entries.Add(new RowEntry { Column = "addressline2", Value = new Value { StringValue = entity.Addressline2 } });
        row.Entries.Add(new RowEntry { Column = "city", Value = new Value { StringValue = entity.City } });
        row.Entries.Add(new RowEntry { Column = "stateprovinceid", Value = new Value { StringValue = entity.Stateprovinceid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "postalcode", Value = new Value { StringValue = entity.Postalcode } });
        row.Entries.Add(new RowEntry { Column = "spatiallocation", Value = new Value { StringValue = entity.Spatiallocation } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
