using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[workorder] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class ProductionWorkorder : BasePostgresTableSchema
{
    public int Workorderid { get; set; }
    public int Productid { get; set; }
    public int Orderqty { get; set; }
    public short Scrappedqty { get; set; }
    public DateTime Startdate { get; set; }
    public DateTime? Enddate { get; set; }
    public DateTime Duedate { get; set; }
    public int? Scrapreasonid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionWorkorderRowsData : BaseTableRowsData
{
    public List<ProductionWorkorder> Rows { get; set; } = new();
}

public class ProductionWorkorderInsertedData : BaseTableInsertedData
{
    public ProductionWorkorder? InsertedRow { get; set; }
}

public class ProductionWorkorderRowData : BaseTableRowData
{
    public ProductionWorkorder? Row { get; set; }
}

public class ProductionWorkorderDataSource : BasePostgresTableDataSource<ProductionWorkorder>
{
    public ProductionWorkorderDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("workorder");
    }

    public async Task<DeletedData> DeleteAsync(int workorderid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("workorderid", workorderid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionWorkorderRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionWorkorder>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionWorkorderRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionWorkorderInsertedData> InsertAsync(ProductionWorkorder entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionWorkorderInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionWorkorderRowData> GetAsync(int workorderid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("workorderid", workorderid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionWorkorderRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionWorkorder entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionWorkorder MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionWorkorder
        {
            Workorderid = dict.TryGetValue("workorderid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Productid = dict.TryGetValue("productid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Orderqty = dict.TryGetValue("orderqty", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : default(int),
            Scrappedqty = dict.TryGetValue("scrappedqty", out var v4) && !string.IsNullOrEmpty(v4) ? (short)Convert.ChangeType(v4, typeof(short)) : default(short),
            Startdate = dict.TryGetValue("startdate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : default(DateTime),
            Enddate = dict.TryGetValue("enddate", out var v6) && !string.IsNullOrEmpty(v6) ? (DateTime)Convert.ChangeType(v6, typeof(DateTime)) : null,
            Duedate = dict.TryGetValue("duedate", out var v7) && !string.IsNullOrEmpty(v7) ? (DateTime)Convert.ChangeType(v7, typeof(DateTime)) : default(DateTime),
            Scrapreasonid = dict.TryGetValue("scrapreasonid", out var v8) && !string.IsNullOrEmpty(v8) ? (int)Convert.ChangeType(v8, typeof(int)) : null,
            Modifieddate = dict.TryGetValue("modifieddate", out var v9) && !string.IsNullOrEmpty(v9) ? (DateTime)Convert.ChangeType(v9, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionWorkorder entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "workorderid", Value = new Value { StringValue = entity.Workorderid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "productid", Value = new Value { StringValue = entity.Productid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "orderqty", Value = new Value { StringValue = entity.Orderqty.ToString() } });
        row.Entries.Add(new RowEntry { Column = "scrappedqty", Value = new Value { StringValue = entity.Scrappedqty.ToString() } });
        row.Entries.Add(new RowEntry { Column = "startdate", Value = new Value { StringValue = entity.Startdate.ToString() } });
        if (entity.Enddate != null)
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = entity.Enddate.Value.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = null } });
        }
        row.Entries.Add(new RowEntry { Column = "duedate", Value = new Value { StringValue = entity.Duedate.ToString() } });
        if (entity.Scrapreasonid != null)
        {
            row.Entries.Add(new RowEntry { Column = "scrapreasonid", Value = new Value { StringValue = entity.Scrapreasonid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "scrapreasonid", Value = new Value { StringValue = null } });
        }
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
