using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[billofmaterials] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:18 PM
// This is only meant to be indicative of the features available in the core product.

public class ProductionBillofmaterials : BasePostgresTableSchema
{
    public int Billofmaterialsid { get; set; }
    public int? Productassemblyid { get; set; }
    public int Componentid { get; set; }
    public DateTime Startdate { get; set; }
    public DateTime? Enddate { get; set; }
    public string Unitmeasurecode { get; set; } = string.Empty;
    public short Bomlevel { get; set; }
    public decimal Perassemblyqty { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionBillofmaterialsRowsData : BaseTableRowsData
{
    public List<ProductionBillofmaterials> Rows { get; set; } = new();
}

public class ProductionBillofmaterialsInsertedData : BaseTableInsertedData
{
    public ProductionBillofmaterials? InsertedRow { get; set; }
}

public class ProductionBillofmaterialsRowData : BaseTableRowData
{
    public ProductionBillofmaterials? Row { get; set; }
}

public class ProductionBillofmaterialsDataSource : BasePostgresTableDataSource<ProductionBillofmaterials>
{
    public ProductionBillofmaterialsDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("billofmaterials");
    }

    public async Task<DeletedData> DeleteAsync(int billofmaterialsid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("billofmaterialsid", billofmaterialsid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionBillofmaterialsRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionBillofmaterials>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionBillofmaterialsRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionBillofmaterialsInsertedData> InsertAsync(ProductionBillofmaterials entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionBillofmaterialsInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionBillofmaterialsRowData> GetAsync(int billofmaterialsid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("billofmaterialsid", billofmaterialsid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionBillofmaterialsRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionBillofmaterials entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionBillofmaterials MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionBillofmaterials
        {
            Billofmaterialsid = dict.TryGetValue("billofmaterialsid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Productassemblyid = dict.TryGetValue("productassemblyid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : null,
            Componentid = dict.TryGetValue("componentid", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : default(int),
            Startdate = dict.TryGetValue("startdate", out var v4) && !string.IsNullOrEmpty(v4) ? (DateTime)Convert.ChangeType(v4, typeof(DateTime)) : default(DateTime),
            Enddate = dict.TryGetValue("enddate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : null,
            Unitmeasurecode = dict.TryGetValue("unitmeasurecode", out var v6) && !string.IsNullOrEmpty(v6) ? (string)Convert.ChangeType(v6, typeof(string)) : default(string),
            Bomlevel = dict.TryGetValue("bomlevel", out var v7) && !string.IsNullOrEmpty(v7) ? (short)Convert.ChangeType(v7, typeof(short)) : default(short),
            Perassemblyqty = dict.TryGetValue("perassemblyqty", out var v8) && !string.IsNullOrEmpty(v8) ? (decimal)Convert.ChangeType(v8, typeof(decimal)) : default(decimal),
            Modifieddate = dict.TryGetValue("modifieddate", out var v9) && !string.IsNullOrEmpty(v9) ? (DateTime)Convert.ChangeType(v9, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionBillofmaterials entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "billofmaterialsid", Value = new Value { StringValue = entity.Billofmaterialsid.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Productassemblyid != null)
        {
            row.Entries.Add(new RowEntry { Column = "productassemblyid", Value = new Value { StringValue = entity.Productassemblyid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "productassemblyid", Value = new Value { StringValue = null } });
        }
        row.Entries.Add(new RowEntry { Column = "componentid", Value = new Value { StringValue = entity.Componentid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "startdate", Value = new Value { StringValue = entity.Startdate.ToString() } });
        if (entity.Enddate != null)
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = entity.Enddate.Value.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "enddate", Value = new Value { StringValue = null } });
        }
        row.Entries.Add(new RowEntry { Column = "unitmeasurecode", Value = new Value { StringValue = entity.Unitmeasurecode } });
        row.Entries.Add(new RowEntry { Column = "bomlevel", Value = new Value { StringValue = entity.Bomlevel.ToString() } });
        row.Entries.Add(new RowEntry { Column = "perassemblyqty", Value = new Value { StringValue = entity.Perassemblyqty.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
