using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[productdocument] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class ProductionProductdocument : BasePostgresTableSchema
{
    public int Productid { get; set; }
    public DateTime Modifieddate { get; set; }
    public string Documentnode { get; set; } = string.Empty;
}

public class ProductionProductdocumentRowsData : BaseTableRowsData
{
    public List<ProductionProductdocument> Rows { get; set; } = new();
}

public class ProductionProductdocumentInsertedData : BaseTableInsertedData
{
    public ProductionProductdocument? InsertedRow { get; set; }
}

public class ProductionProductdocumentRowData : BaseTableRowData
{
    public ProductionProductdocument? Row { get; set; }
}

public class ProductionProductdocumentDataSource : BasePostgresTableDataSource<ProductionProductdocument>
{
    public ProductionProductdocumentDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("productdocument");
    }

    public async Task<DeletedData> DeleteAsync(int productid, string documentnode, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("productid", productid.ToString());
        req.PrimaryKeyValues.Add("documentnode", documentnode.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionProductdocumentRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionProductdocument>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionProductdocumentRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductdocumentInsertedData> InsertAsync(ProductionProductdocument entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductdocumentInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductdocumentRowData> GetAsync(int productid, string documentnode, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("productid", productid.ToString());
        req.PrimaryKeyValues.Add("documentnode", documentnode.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductdocumentRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionProductdocument entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionProductdocument MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionProductdocument
        {
            Productid = dict.TryGetValue("productid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Modifieddate = dict.TryGetValue("modifieddate", out var v2) && !string.IsNullOrEmpty(v2) ? (DateTime)Convert.ChangeType(v2, typeof(DateTime)) : default(DateTime),
            Documentnode = dict.TryGetValue("documentnode", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
        };
    }

    protected override Row MapTableEntityToRow(ProductionProductdocument entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "productid", Value = new Value { StringValue = entity.Productid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "documentnode", Value = new Value { StringValue = entity.Documentnode.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
