using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[productdescription] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:27 PM
// This is only meant to be indicative of the features available in the core product.

public class ProductionProductdescription : BasePostgresTableSchema
{
    public int Productdescriptionid { get; set; }
    public string Description { get; set; } = string.Empty;
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionProductdescriptionRowsData : BaseTableRowsData
{
    public List<ProductionProductdescription> Rows { get; set; } = new();
}

public class ProductionProductdescriptionInsertedData : BaseTableInsertedData
{
    public ProductionProductdescription? InsertedRow { get; set; }
}

public class ProductionProductdescriptionRowData : BaseTableRowData
{
    public ProductionProductdescription? Row { get; set; }
}

public class ProductionProductdescriptionDataSource : BasePostgresTableDataSource<ProductionProductdescription>
{
    public ProductionProductdescriptionDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("productdescription");
    }

    public async Task<DeletedData> DeleteAsync(int productdescriptionid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("productdescriptionid", productdescriptionid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionProductdescriptionRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionProductdescription>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionProductdescriptionRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductdescriptionInsertedData> InsertAsync(ProductionProductdescription entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductdescriptionInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductdescriptionRowData> GetAsync(int productdescriptionid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("productdescriptionid", productdescriptionid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductdescriptionRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionProductdescription entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionProductdescription MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionProductdescription
        {
            Productdescriptionid = dict.TryGetValue("productdescriptionid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Description = dict.TryGetValue("description", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Rowguid = dict.TryGetValue("rowguid", out var v3) && !string.IsNullOrEmpty(v3) ? (Guid)Convert.ChangeType(v3, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v4) && !string.IsNullOrEmpty(v4) ? (DateTime)Convert.ChangeType(v4, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionProductdescription entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "productdescriptionid", Value = new Value { StringValue = entity.Productdescriptionid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "description", Value = new Value { StringValue = entity.Description } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
