using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[transactionhistory] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:28 PM
// This is only meant to be indicative of the features available in the core product.

public class ProductionTransactionhistory : BasePostgresTableSchema
{
    public int Transactionid { get; set; }
    public int Productid { get; set; }
    public int Referenceorderid { get; set; }
    public int Referenceorderlineid { get; set; }
    public DateTime Transactiondate { get; set; }
    public string Transactiontype { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public decimal Actualcost { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionTransactionhistoryRowsData : BaseTableRowsData
{
    public List<ProductionTransactionhistory> Rows { get; set; } = new();
}

public class ProductionTransactionhistoryInsertedData : BaseTableInsertedData
{
    public ProductionTransactionhistory? InsertedRow { get; set; }
}

public class ProductionTransactionhistoryRowData : BaseTableRowData
{
    public ProductionTransactionhistory? Row { get; set; }
}

public class ProductionTransactionhistoryDataSource : BasePostgresTableDataSource<ProductionTransactionhistory>
{
    public ProductionTransactionhistoryDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("transactionhistory");
    }

    public async Task<DeletedData> DeleteAsync(int transactionid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("transactionid", transactionid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionTransactionhistoryRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionTransactionhistory>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionTransactionhistoryRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionTransactionhistoryInsertedData> InsertAsync(ProductionTransactionhistory entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionTransactionhistoryInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionTransactionhistoryRowData> GetAsync(int transactionid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("transactionid", transactionid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionTransactionhistoryRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionTransactionhistory entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionTransactionhistory MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionTransactionhistory
        {
            Transactionid = dict.TryGetValue("transactionid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Productid = dict.TryGetValue("productid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Referenceorderid = dict.TryGetValue("referenceorderid", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : default(int),
            Referenceorderlineid = dict.TryGetValue("referenceorderlineid", out var v4) && !string.IsNullOrEmpty(v4) ? (int)Convert.ChangeType(v4, typeof(int)) : default(int),
            Transactiondate = dict.TryGetValue("transactiondate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : default(DateTime),
            Transactiontype = dict.TryGetValue("transactiontype", out var v6) && !string.IsNullOrEmpty(v6) ? (string)Convert.ChangeType(v6, typeof(string)) : default(string),
            Quantity = dict.TryGetValue("quantity", out var v7) && !string.IsNullOrEmpty(v7) ? (int)Convert.ChangeType(v7, typeof(int)) : default(int),
            Actualcost = dict.TryGetValue("actualcost", out var v8) && !string.IsNullOrEmpty(v8) ? (decimal)Convert.ChangeType(v8, typeof(decimal)) : default(decimal),
            Modifieddate = dict.TryGetValue("modifieddate", out var v9) && !string.IsNullOrEmpty(v9) ? (DateTime)Convert.ChangeType(v9, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionTransactionhistory entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "transactionid", Value = new Value { StringValue = entity.Transactionid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "productid", Value = new Value { StringValue = entity.Productid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "referenceorderid", Value = new Value { StringValue = entity.Referenceorderid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "referenceorderlineid", Value = new Value { StringValue = entity.Referenceorderlineid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "transactiondate", Value = new Value { StringValue = entity.Transactiondate.ToString() } });
        row.Entries.Add(new RowEntry { Column = "transactiontype", Value = new Value { StringValue = entity.Transactiontype } });
        row.Entries.Add(new RowEntry { Column = "quantity", Value = new Value { StringValue = entity.Quantity.ToString() } });
        row.Entries.Add(new RowEntry { Column = "actualcost", Value = new Value { StringValue = entity.Actualcost.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
