using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[productphoto] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:19 PM
// This is only meant to be indicative of the features available in the core product.

public class ProductionProductphoto : BasePostgresTableSchema
{
    public int Productphotoid { get; set; }
    public byte[]? Thumbnailphoto { get; set; }
    public string? Thumbnailphotofilename { get; set; }
    public byte[]? Largephoto { get; set; }
    public string? Largephotofilename { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionProductphotoRowsData : BaseTableRowsData
{
    public List<ProductionProductphoto> Rows { get; set; } = new();
}

public class ProductionProductphotoInsertedData : BaseTableInsertedData
{
    public ProductionProductphoto? InsertedRow { get; set; }
}

public class ProductionProductphotoRowData : BaseTableRowData
{
    public ProductionProductphoto? Row { get; set; }
}

public class ProductionProductphotoDataSource : BasePostgresTableDataSource<ProductionProductphoto>
{
    public ProductionProductphotoDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("productphoto");
    }

    public async Task<DeletedData> DeleteAsync(int productphotoid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("productphotoid", productphotoid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionProductphotoRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionProductphoto>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionProductphotoRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductphotoInsertedData> InsertAsync(ProductionProductphoto entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductphotoInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductphotoRowData> GetAsync(int productphotoid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("productphotoid", productphotoid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductphotoRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionProductphoto entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionProductphoto MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionProductphoto
        {
            Productphotoid = dict.TryGetValue("productphotoid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Thumbnailphoto = dict.TryGetValue("thumbnailphoto", out var v2) && !string.IsNullOrEmpty(v2) ? (byte[])Convert.ChangeType(v2, typeof(byte[])) : default(byte[]),
            Thumbnailphotofilename = dict.TryGetValue("thumbnailphotofilename", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : null,
            Largephoto = dict.TryGetValue("largephoto", out var v4) && !string.IsNullOrEmpty(v4) ? (byte[])Convert.ChangeType(v4, typeof(byte[])) : default(byte[]),
            Largephotofilename = dict.TryGetValue("largephotofilename", out var v5) && !string.IsNullOrEmpty(v5) ? (string)Convert.ChangeType(v5, typeof(string)) : null,
            Modifieddate = dict.TryGetValue("modifieddate", out var v6) && !string.IsNullOrEmpty(v6) ? (DateTime)Convert.ChangeType(v6, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionProductphoto entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "productphotoid", Value = new Value { StringValue = entity.Productphotoid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "thumbnailphoto", Value = new Value { StringValue = entity.Thumbnailphoto != null ? Convert.ToBase64String(entity.Thumbnailphoto) : null } });
        row.Entries.Add(new RowEntry { Column = "thumbnailphotofilename", Value = new Value { StringValue = entity.Thumbnailphotofilename } });
        row.Entries.Add(new RowEntry { Column = "largephoto", Value = new Value { StringValue = entity.Largephoto != null ? Convert.ToBase64String(entity.Largephoto) : null } });
        row.Entries.Add(new RowEntry { Column = "largephotofilename", Value = new Value { StringValue = entity.Largephotofilename } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
