using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[unitmeasure] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class ProductionUnitmeasure : BasePostgresTableSchema
{
    public string Unitmeasurecode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public DateTime Modifieddate { get; set; }
}

public class ProductionUnitmeasureRowsData : BaseTableRowsData
{
    public List<ProductionUnitmeasure> Rows { get; set; } = new();
}

public class ProductionUnitmeasureInsertedData : BaseTableInsertedData
{
    public ProductionUnitmeasure? InsertedRow { get; set; }
}

public class ProductionUnitmeasureRowData : BaseTableRowData
{
    public ProductionUnitmeasure? Row { get; set; }
}

public class ProductionUnitmeasureDataSource : BasePostgresTableDataSource<ProductionUnitmeasure>
{
    public ProductionUnitmeasureDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("unitmeasure");
    }

    public async Task<DeletedData> DeleteAsync(string unitmeasurecode, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("unitmeasurecode", unitmeasurecode.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionUnitmeasureRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionUnitmeasure>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionUnitmeasureRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionUnitmeasureInsertedData> InsertAsync(ProductionUnitmeasure entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionUnitmeasureInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionUnitmeasureRowData> GetAsync(string unitmeasurecode, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("unitmeasurecode", unitmeasurecode.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionUnitmeasureRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionUnitmeasure entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionUnitmeasure MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionUnitmeasure
        {
            Unitmeasurecode = dict.TryGetValue("unitmeasurecode", out var v1) && !string.IsNullOrEmpty(v1) ? (string)Convert.ChangeType(v1, typeof(string)) : default(string),
            Name = dict.TryGetValue("name", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Modifieddate = dict.TryGetValue("modifieddate", out var v3) && !string.IsNullOrEmpty(v3) ? (DateTime)Convert.ChangeType(v3, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionUnitmeasure entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "unitmeasurecode", Value = new Value { StringValue = entity.Unitmeasurecode.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
