using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[productmodelproductdescriptionculture] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:19 PM
// This is only meant to be indicative of the features available in the core product.

public class ProductionProductmodelproductdescriptionculture : BasePostgresTableSchema
{
    public int Productmodelid { get; set; }
    public int Productdescriptionid { get; set; }
    public string Cultureid { get; set; } = string.Empty;
    public DateTime Modifieddate { get; set; }
}

public class ProductionProductmodelproductdescriptioncultureRowsData : BaseTableRowsData
{
    public List<ProductionProductmodelproductdescriptionculture> Rows { get; set; } = new();
}

public class ProductionProductmodelproductdescriptioncultureInsertedData : BaseTableInsertedData
{
    public ProductionProductmodelproductdescriptionculture? InsertedRow { get; set; }
}

public class ProductionProductmodelproductdescriptioncultureRowData : BaseTableRowData
{
    public ProductionProductmodelproductdescriptionculture? Row { get; set; }
}

public class ProductionProductmodelproductdescriptioncultureDataSource : BasePostgresTableDataSource<ProductionProductmodelproductdescriptionculture>
{
    public ProductionProductmodelproductdescriptioncultureDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("productmodelproductdescriptionculture");
    }

    public async Task<DeletedData> DeleteAsync(int productmodelid, int productdescriptionid, string cultureid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("productmodelid", productmodelid.ToString());
        req.PrimaryKeyValues.Add("productdescriptionid", productdescriptionid.ToString());
        req.PrimaryKeyValues.Add("cultureid", cultureid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionProductmodelproductdescriptioncultureRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionProductmodelproductdescriptionculture>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionProductmodelproductdescriptioncultureRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductmodelproductdescriptioncultureInsertedData> InsertAsync(ProductionProductmodelproductdescriptionculture entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductmodelproductdescriptioncultureInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductmodelproductdescriptioncultureRowData> GetAsync(int productmodelid, int productdescriptionid, string cultureid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("productmodelid", productmodelid.ToString());
        req.PrimaryKeyValues.Add("productdescriptionid", productdescriptionid.ToString());
        req.PrimaryKeyValues.Add("cultureid", cultureid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductmodelproductdescriptioncultureRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionProductmodelproductdescriptionculture entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionProductmodelproductdescriptionculture MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionProductmodelproductdescriptionculture
        {
            Productmodelid = dict.TryGetValue("productmodelid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Productdescriptionid = dict.TryGetValue("productdescriptionid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Cultureid = dict.TryGetValue("cultureid", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Modifieddate = dict.TryGetValue("modifieddate", out var v4) && !string.IsNullOrEmpty(v4) ? (DateTime)Convert.ChangeType(v4, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionProductmodelproductdescriptionculture entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "productmodelid", Value = new Value { StringValue = entity.Productmodelid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "productdescriptionid", Value = new Value { StringValue = entity.Productdescriptionid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "cultureid", Value = new Value { StringValue = entity.Cultureid.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
