using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [production].[productinventory] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class ProductionProductinventory : BasePostgresTableSchema
{
    public int Productid { get; set; }
    public int Locationid { get; set; }
    public string Shelf { get; set; } = string.Empty;
    public short Bin { get; set; }
    public short Quantity { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class ProductionProductinventoryRowsData : BaseTableRowsData
{
    public List<ProductionProductinventory> Rows { get; set; } = new();
}

public class ProductionProductinventoryInsertedData : BaseTableInsertedData
{
    public ProductionProductinventory? InsertedRow { get; set; }
}

public class ProductionProductinventoryRowData : BaseTableRowData
{
    public ProductionProductinventory? Row { get; set; }
}

public class ProductionProductinventoryDataSource : BasePostgresTableDataSource<ProductionProductinventory>
{
    public ProductionProductinventoryDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("production");
        _encTable = RedflyEncryption.EncryptToString("productinventory");
    }

    public async Task<DeletedData> DeleteAsync(int productid, int locationid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("productid", productid.ToString());
        req.PrimaryKeyValues.Add("locationid", locationid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<ProductionProductinventoryRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<ProductionProductinventory>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new ProductionProductinventoryRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductinventoryInsertedData> InsertAsync(ProductionProductinventory entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductinventoryInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<ProductionProductinventoryRowData> GetAsync(int productid, int locationid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("productid", productid.ToString());
        req.PrimaryKeyValues.Add("locationid", locationid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new ProductionProductinventoryRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(ProductionProductinventory entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override ProductionProductinventory MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new ProductionProductinventory
        {
            Productid = dict.TryGetValue("productid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Locationid = dict.TryGetValue("locationid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Shelf = dict.TryGetValue("shelf", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Bin = dict.TryGetValue("bin", out var v4) && !string.IsNullOrEmpty(v4) ? (short)Convert.ChangeType(v4, typeof(short)) : default(short),
            Quantity = dict.TryGetValue("quantity", out var v5) && !string.IsNullOrEmpty(v5) ? (short)Convert.ChangeType(v5, typeof(short)) : default(short),
            Rowguid = dict.TryGetValue("rowguid", out var v6) && !string.IsNullOrEmpty(v6) ? (Guid)Convert.ChangeType(v6, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v7) && !string.IsNullOrEmpty(v7) ? (DateTime)Convert.ChangeType(v7, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(ProductionProductinventory entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "productid", Value = new Value { StringValue = entity.Productid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "locationid", Value = new Value { StringValue = entity.Locationid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "shelf", Value = new Value { StringValue = entity.Shelf } });
        row.Entries.Add(new RowEntry { Column = "bin", Value = new Value { StringValue = entity.Bin.ToString() } });
        row.Entries.Add(new RowEntry { Column = "quantity", Value = new Value { StringValue = entity.Quantity.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
