using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [purchasing].[vendor] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:19 PM
// This is only meant to be indicative of the features available in the core product.

public class PurchasingVendor : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public string Accountnumber { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public short Creditrating { get; set; }
    public bool Preferredvendorstatus { get; set; }
    public bool Activeflag { get; set; }
    public string? Purchasingwebserviceurl { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class PurchasingVendorRowsData : BaseTableRowsData
{
    public List<PurchasingVendor> Rows { get; set; } = new();
}

public class PurchasingVendorInsertedData : BaseTableInsertedData
{
    public PurchasingVendor? InsertedRow { get; set; }
}

public class PurchasingVendorRowData : BaseTableRowData
{
    public PurchasingVendor? Row { get; set; }
}

public class PurchasingVendorDataSource : BasePostgresTableDataSource<PurchasingVendor>
{
    public PurchasingVendorDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("purchasing");
        _encTable = RedflyEncryption.EncryptToString("vendor");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<PurchasingVendorRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<PurchasingVendor>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new PurchasingVendorRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<PurchasingVendorInsertedData> InsertAsync(PurchasingVendor entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new PurchasingVendorInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<PurchasingVendorRowData> GetAsync(int businessentityid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new PurchasingVendorRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(PurchasingVendor entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override PurchasingVendor MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new PurchasingVendor
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Accountnumber = dict.TryGetValue("accountnumber", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Name = dict.TryGetValue("name", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Creditrating = dict.TryGetValue("creditrating", out var v4) && !string.IsNullOrEmpty(v4) ? (short)Convert.ChangeType(v4, typeof(short)) : default(short),
            Preferredvendorstatus = dict.TryGetValue("preferredvendorstatus", out var v5) && !string.IsNullOrEmpty(v5) ? (bool)Convert.ChangeType(v5, typeof(bool)) : default(bool),
            Activeflag = dict.TryGetValue("activeflag", out var v6) && !string.IsNullOrEmpty(v6) ? (bool)Convert.ChangeType(v6, typeof(bool)) : default(bool),
            Purchasingwebserviceurl = dict.TryGetValue("purchasingwebserviceurl", out var v7) && !string.IsNullOrEmpty(v7) ? (string)Convert.ChangeType(v7, typeof(string)) : null,
            Modifieddate = dict.TryGetValue("modifieddate", out var v8) && !string.IsNullOrEmpty(v8) ? (DateTime)Convert.ChangeType(v8, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(PurchasingVendor entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "accountnumber", Value = new Value { StringValue = entity.Accountnumber } });
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "creditrating", Value = new Value { StringValue = entity.Creditrating.ToString() } });
        row.Entries.Add(new RowEntry { Column = "preferredvendorstatus", Value = new Value { StringValue = entity.Preferredvendorstatus.ToString() } });
        row.Entries.Add(new RowEntry { Column = "activeflag", Value = new Value { StringValue = entity.Activeflag.ToString() } });
        row.Entries.Add(new RowEntry { Column = "purchasingwebserviceurl", Value = new Value { StringValue = entity.Purchasingwebserviceurl } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
