using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salestaxrate] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:29 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesSalestaxrate : BasePostgresTableSchema
{
    public int Salestaxrateid { get; set; }
    public int Stateprovinceid { get; set; }
    public short Taxtype { get; set; }
    public decimal Taxrate { get; set; }
    public string Name { get; set; } = string.Empty;
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalestaxrateRowsData : BaseTableRowsData
{
    public List<SalesSalestaxrate> Rows { get; set; } = new();
}

public class SalesSalestaxrateInsertedData : BaseTableInsertedData
{
    public SalesSalestaxrate? InsertedRow { get; set; }
}

public class SalesSalestaxrateRowData : BaseTableRowData
{
    public SalesSalestaxrate? Row { get; set; }
}

public class SalesSalestaxrateDataSource : BasePostgresTableDataSource<SalesSalestaxrate>
{
    public SalesSalestaxrateDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salestaxrate");
    }

    public async Task<DeletedData> DeleteAsync(int salestaxrateid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("salestaxrateid", salestaxrateid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalestaxrateRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalestaxrate>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalestaxrateRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalestaxrateInsertedData> InsertAsync(SalesSalestaxrate entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalestaxrateInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalestaxrateRowData> GetAsync(int salestaxrateid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("salestaxrateid", salestaxrateid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalestaxrateRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalestaxrate entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalestaxrate MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalestaxrate
        {
            Salestaxrateid = dict.TryGetValue("salestaxrateid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Stateprovinceid = dict.TryGetValue("stateprovinceid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Taxtype = dict.TryGetValue("taxtype", out var v3) && !string.IsNullOrEmpty(v3) ? (short)Convert.ChangeType(v3, typeof(short)) : default(short),
            Taxrate = dict.TryGetValue("taxrate", out var v4) && !string.IsNullOrEmpty(v4) ? (decimal)Convert.ChangeType(v4, typeof(decimal)) : default(decimal),
            Name = dict.TryGetValue("name", out var v5) && !string.IsNullOrEmpty(v5) ? (string)Convert.ChangeType(v5, typeof(string)) : default(string),
            Rowguid = dict.TryGetValue("rowguid", out var v6) && !string.IsNullOrEmpty(v6) ? (Guid)Convert.ChangeType(v6, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v7) && !string.IsNullOrEmpty(v7) ? (DateTime)Convert.ChangeType(v7, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalestaxrate entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "salestaxrateid", Value = new Value { StringValue = entity.Salestaxrateid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "stateprovinceid", Value = new Value { StringValue = entity.Stateprovinceid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "taxtype", Value = new Value { StringValue = entity.Taxtype.ToString() } });
        row.Entries.Add(new RowEntry { Column = "taxrate", Value = new Value { StringValue = entity.Taxrate.ToString() } });
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
