using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[currencyrate] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class SalesCurrencyrate : BasePostgresTableSchema
{
    public int Currencyrateid { get; set; }
    public DateTime Currencyratedate { get; set; }
    public string Fromcurrencycode { get; set; } = string.Empty;
    public string Tocurrencycode { get; set; } = string.Empty;
    public decimal Averagerate { get; set; }
    public decimal Endofdayrate { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesCurrencyrateRowsData : BaseTableRowsData
{
    public List<SalesCurrencyrate> Rows { get; set; } = new();
}

public class SalesCurrencyrateInsertedData : BaseTableInsertedData
{
    public SalesCurrencyrate? InsertedRow { get; set; }
}

public class SalesCurrencyrateRowData : BaseTableRowData
{
    public SalesCurrencyrate? Row { get; set; }
}

public class SalesCurrencyrateDataSource : BasePostgresTableDataSource<SalesCurrencyrate>
{
    public SalesCurrencyrateDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("currencyrate");
    }

    public async Task<DeletedData> DeleteAsync(int currencyrateid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("currencyrateid", currencyrateid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesCurrencyrateRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesCurrencyrate>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesCurrencyrateRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesCurrencyrateInsertedData> InsertAsync(SalesCurrencyrate entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesCurrencyrateInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesCurrencyrateRowData> GetAsync(int currencyrateid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("currencyrateid", currencyrateid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesCurrencyrateRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesCurrencyrate entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesCurrencyrate MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesCurrencyrate
        {
            Currencyrateid = dict.TryGetValue("currencyrateid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Currencyratedate = dict.TryGetValue("currencyratedate", out var v2) && !string.IsNullOrEmpty(v2) ? (DateTime)Convert.ChangeType(v2, typeof(DateTime)) : default(DateTime),
            Fromcurrencycode = dict.TryGetValue("fromcurrencycode", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Tocurrencycode = dict.TryGetValue("tocurrencycode", out var v4) && !string.IsNullOrEmpty(v4) ? (string)Convert.ChangeType(v4, typeof(string)) : default(string),
            Averagerate = dict.TryGetValue("averagerate", out var v5) && !string.IsNullOrEmpty(v5) ? (decimal)Convert.ChangeType(v5, typeof(decimal)) : default(decimal),
            Endofdayrate = dict.TryGetValue("endofdayrate", out var v6) && !string.IsNullOrEmpty(v6) ? (decimal)Convert.ChangeType(v6, typeof(decimal)) : default(decimal),
            Modifieddate = dict.TryGetValue("modifieddate", out var v7) && !string.IsNullOrEmpty(v7) ? (DateTime)Convert.ChangeType(v7, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesCurrencyrate entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "currencyrateid", Value = new Value { StringValue = entity.Currencyrateid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "currencyratedate", Value = new Value { StringValue = entity.Currencyratedate.ToString() } });
        row.Entries.Add(new RowEntry { Column = "fromcurrencycode", Value = new Value { StringValue = entity.Fromcurrencycode } });
        row.Entries.Add(new RowEntry { Column = "tocurrencycode", Value = new Value { StringValue = entity.Tocurrencycode } });
        row.Entries.Add(new RowEntry { Column = "averagerate", Value = new Value { StringValue = entity.Averagerate.ToString() } });
        row.Entries.Add(new RowEntry { Column = "endofdayrate", Value = new Value { StringValue = entity.Endofdayrate.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
