using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[customer] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class SalesCustomer : BasePostgresTableSchema
{
    public int Customerid { get; set; }
    public int? Personid { get; set; }
    public int? Storeid { get; set; }
    public int? Territoryid { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesCustomerRowsData : BaseTableRowsData
{
    public List<SalesCustomer> Rows { get; set; } = new();
}

public class SalesCustomerInsertedData : BaseTableInsertedData
{
    public SalesCustomer? InsertedRow { get; set; }
}

public class SalesCustomerRowData : BaseTableRowData
{
    public SalesCustomer? Row { get; set; }
}

public class SalesCustomerDataSource : BasePostgresTableDataSource<SalesCustomer>
{
    public SalesCustomerDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("customer");
    }

    public async Task<DeletedData> DeleteAsync(int customerid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("customerid", customerid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesCustomerRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesCustomer>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesCustomerRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesCustomerInsertedData> InsertAsync(SalesCustomer entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesCustomerInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesCustomerRowData> GetAsync(int customerid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("customerid", customerid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesCustomerRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesCustomer entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesCustomer MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesCustomer
        {
            Customerid = dict.TryGetValue("customerid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Personid = dict.TryGetValue("personid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : null,
            Storeid = dict.TryGetValue("storeid", out var v3) && !string.IsNullOrEmpty(v3) ? (int)Convert.ChangeType(v3, typeof(int)) : null,
            Territoryid = dict.TryGetValue("territoryid", out var v4) && !string.IsNullOrEmpty(v4) ? (int)Convert.ChangeType(v4, typeof(int)) : null,
            Rowguid = dict.TryGetValue("rowguid", out var v5) && !string.IsNullOrEmpty(v5) ? (Guid)Convert.ChangeType(v5, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v6) && !string.IsNullOrEmpty(v6) ? (DateTime)Convert.ChangeType(v6, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesCustomer entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "customerid", Value = new Value { StringValue = entity.Customerid.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Personid != null)
        {
            row.Entries.Add(new RowEntry { Column = "personid", Value = new Value { StringValue = entity.Personid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "personid", Value = new Value { StringValue = null } });
        }
        if (entity.Storeid != null)
        {
            row.Entries.Add(new RowEntry { Column = "storeid", Value = new Value { StringValue = entity.Storeid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "storeid", Value = new Value { StringValue = null } });
        }
        if (entity.Territoryid != null)
        {
            row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = entity.Territoryid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = null } });
        }
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
