using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salesorderdetail] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:29 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesSalesorderdetail : BasePostgresTableSchema
{
    public int Salesorderid { get; set; }
    public int Salesorderdetailid { get; set; }
    public string? Carriertrackingnumber { get; set; }
    public short Orderqty { get; set; }
    public int Productid { get; set; }
    public int Specialofferid { get; set; }
    public decimal Unitprice { get; set; }
    public decimal Unitpricediscount { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalesorderdetailRowsData : BaseTableRowsData
{
    public List<SalesSalesorderdetail> Rows { get; set; } = new();
}

public class SalesSalesorderdetailInsertedData : BaseTableInsertedData
{
    public SalesSalesorderdetail? InsertedRow { get; set; }
}

public class SalesSalesorderdetailRowData : BaseTableRowData
{
    public SalesSalesorderdetail? Row { get; set; }
}

public class SalesSalesorderdetailDataSource : BasePostgresTableDataSource<SalesSalesorderdetail>
{
    public SalesSalesorderdetailDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salesorderdetail");
    }

    public async Task<DeletedData> DeleteAsync(int salesorderid, int salesorderdetailid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("salesorderid", salesorderid.ToString());
        req.PrimaryKeyValues.Add("salesorderdetailid", salesorderdetailid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalesorderdetailRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalesorderdetail>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalesorderdetailRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesorderdetailInsertedData> InsertAsync(SalesSalesorderdetail entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesorderdetailInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesorderdetailRowData> GetAsync(int salesorderid, int salesorderdetailid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("salesorderid", salesorderid.ToString());
        req.PrimaryKeyValues.Add("salesorderdetailid", salesorderdetailid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesorderdetailRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalesorderdetail entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalesorderdetail MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalesorderdetail
        {
            Salesorderid = dict.TryGetValue("salesorderid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Salesorderdetailid = dict.TryGetValue("salesorderdetailid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Carriertrackingnumber = dict.TryGetValue("carriertrackingnumber", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : null,
            Orderqty = dict.TryGetValue("orderqty", out var v4) && !string.IsNullOrEmpty(v4) ? (short)Convert.ChangeType(v4, typeof(short)) : default(short),
            Productid = dict.TryGetValue("productid", out var v5) && !string.IsNullOrEmpty(v5) ? (int)Convert.ChangeType(v5, typeof(int)) : default(int),
            Specialofferid = dict.TryGetValue("specialofferid", out var v6) && !string.IsNullOrEmpty(v6) ? (int)Convert.ChangeType(v6, typeof(int)) : default(int),
            Unitprice = dict.TryGetValue("unitprice", out var v7) && !string.IsNullOrEmpty(v7) ? (decimal)Convert.ChangeType(v7, typeof(decimal)) : default(decimal),
            Unitpricediscount = dict.TryGetValue("unitpricediscount", out var v8) && !string.IsNullOrEmpty(v8) ? (decimal)Convert.ChangeType(v8, typeof(decimal)) : default(decimal),
            Rowguid = dict.TryGetValue("rowguid", out var v9) && !string.IsNullOrEmpty(v9) ? (Guid)Convert.ChangeType(v9, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v10) && !string.IsNullOrEmpty(v10) ? (DateTime)Convert.ChangeType(v10, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalesorderdetail entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "salesorderid", Value = new Value { StringValue = entity.Salesorderid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "salesorderdetailid", Value = new Value { StringValue = entity.Salesorderdetailid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "carriertrackingnumber", Value = new Value { StringValue = entity.Carriertrackingnumber } });
        row.Entries.Add(new RowEntry { Column = "orderqty", Value = new Value { StringValue = entity.Orderqty.ToString() } });
        row.Entries.Add(new RowEntry { Column = "productid", Value = new Value { StringValue = entity.Productid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "specialofferid", Value = new Value { StringValue = entity.Specialofferid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "unitprice", Value = new Value { StringValue = entity.Unitprice.ToString() } });
        row.Entries.Add(new RowEntry { Column = "unitpricediscount", Value = new Value { StringValue = entity.Unitpricediscount.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
