using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salesorderheadersalesreason] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:20 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesSalesorderheadersalesreason : BasePostgresTableSchema
{
    public int Salesorderid { get; set; }
    public int Salesreasonid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalesorderheadersalesreasonRowsData : BaseTableRowsData
{
    public List<SalesSalesorderheadersalesreason> Rows { get; set; } = new();
}

public class SalesSalesorderheadersalesreasonInsertedData : BaseTableInsertedData
{
    public SalesSalesorderheadersalesreason? InsertedRow { get; set; }
}

public class SalesSalesorderheadersalesreasonRowData : BaseTableRowData
{
    public SalesSalesorderheadersalesreason? Row { get; set; }
}

public class SalesSalesorderheadersalesreasonDataSource : BasePostgresTableDataSource<SalesSalesorderheadersalesreason>
{
    public SalesSalesorderheadersalesreasonDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salesorderheadersalesreason");
    }

    public async Task<DeletedData> DeleteAsync(int salesorderid, int salesreasonid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("salesorderid", salesorderid.ToString());
        req.PrimaryKeyValues.Add("salesreasonid", salesreasonid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalesorderheadersalesreasonRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalesorderheadersalesreason>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalesorderheadersalesreasonRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesorderheadersalesreasonInsertedData> InsertAsync(SalesSalesorderheadersalesreason entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesorderheadersalesreasonInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesorderheadersalesreasonRowData> GetAsync(int salesorderid, int salesreasonid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("salesorderid", salesorderid.ToString());
        req.PrimaryKeyValues.Add("salesreasonid", salesreasonid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesorderheadersalesreasonRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalesorderheadersalesreason entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalesorderheadersalesreason MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalesorderheadersalesreason
        {
            Salesorderid = dict.TryGetValue("salesorderid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Salesreasonid = dict.TryGetValue("salesreasonid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : default(int),
            Modifieddate = dict.TryGetValue("modifieddate", out var v3) && !string.IsNullOrEmpty(v3) ? (DateTime)Convert.ChangeType(v3, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalesorderheadersalesreason entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "salesorderid", Value = new Value { StringValue = entity.Salesorderid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "salesreasonid", Value = new Value { StringValue = entity.Salesreasonid.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
