using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salespersonquotahistory] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:21:29 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesSalespersonquotahistory : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public DateTime Quotadate { get; set; }
    public decimal Salesquota { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalespersonquotahistoryRowsData : BaseTableRowsData
{
    public List<SalesSalespersonquotahistory> Rows { get; set; } = new();
}

public class SalesSalespersonquotahistoryInsertedData : BaseTableInsertedData
{
    public SalesSalespersonquotahistory? InsertedRow { get; set; }
}

public class SalesSalespersonquotahistoryRowData : BaseTableRowData
{
    public SalesSalespersonquotahistory? Row { get; set; }
}

public class SalesSalespersonquotahistoryDataSource : BasePostgresTableDataSource<SalesSalespersonquotahistory>
{
    public SalesSalespersonquotahistoryDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salespersonquotahistory");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, DateTime quotadate, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("quotadate", quotadate.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalespersonquotahistoryRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalespersonquotahistory>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalespersonquotahistoryRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalespersonquotahistoryInsertedData> InsertAsync(SalesSalespersonquotahistory entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalespersonquotahistoryInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalespersonquotahistoryRowData> GetAsync(int businessentityid, DateTime quotadate, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        req.PrimaryKeyValues.Add("quotadate", quotadate.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalespersonquotahistoryRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalespersonquotahistory entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalespersonquotahistory MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalespersonquotahistory
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Quotadate = dict.TryGetValue("quotadate", out var v2) && !string.IsNullOrEmpty(v2) ? (DateTime)Convert.ChangeType(v2, typeof(DateTime)) : default(DateTime),
            Salesquota = dict.TryGetValue("salesquota", out var v3) && !string.IsNullOrEmpty(v3) ? (decimal)Convert.ChangeType(v3, typeof(decimal)) : default(decimal),
            Rowguid = dict.TryGetValue("rowguid", out var v4) && !string.IsNullOrEmpty(v4) ? (Guid)Convert.ChangeType(v4, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v5) && !string.IsNullOrEmpty(v5) ? (DateTime)Convert.ChangeType(v5, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalespersonquotahistory entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });
        row.Entries.Add(new RowEntry { Column = "quotadate", Value = new Value { StringValue = entity.Quotadate.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "salesquota", Value = new Value { StringValue = entity.Salesquota.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
