using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salesperson] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class SalesSalesperson : BasePostgresTableSchema
{
    public int Businessentityid { get; set; }
    public int? Territoryid { get; set; }
    public decimal? Salesquota { get; set; }
    public decimal Bonus { get; set; }
    public decimal Commissionpct { get; set; }
    public decimal Salesytd { get; set; }
    public decimal Saleslastyear { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalespersonRowsData : BaseTableRowsData
{
    public List<SalesSalesperson> Rows { get; set; } = new();
}

public class SalesSalespersonInsertedData : BaseTableInsertedData
{
    public SalesSalesperson? InsertedRow { get; set; }
}

public class SalesSalespersonRowData : BaseTableRowData
{
    public SalesSalesperson? Row { get; set; }
}

public class SalesSalespersonDataSource : BasePostgresTableDataSource<SalesSalesperson>
{
    public SalesSalespersonDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salesperson");
    }

    public async Task<DeletedData> DeleteAsync(int businessentityid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalespersonRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalesperson>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalespersonRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalespersonInsertedData> InsertAsync(SalesSalesperson entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalespersonInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalespersonRowData> GetAsync(int businessentityid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("businessentityid", businessentityid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalespersonRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalesperson entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalesperson MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalesperson
        {
            Businessentityid = dict.TryGetValue("businessentityid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Territoryid = dict.TryGetValue("territoryid", out var v2) && !string.IsNullOrEmpty(v2) ? (int)Convert.ChangeType(v2, typeof(int)) : null,
            Salesquota = dict.TryGetValue("salesquota", out var v3) && !string.IsNullOrEmpty(v3) ? (decimal)Convert.ChangeType(v3, typeof(decimal)) : null,
            Bonus = dict.TryGetValue("bonus", out var v4) && !string.IsNullOrEmpty(v4) ? (decimal)Convert.ChangeType(v4, typeof(decimal)) : default(decimal),
            Commissionpct = dict.TryGetValue("commissionpct", out var v5) && !string.IsNullOrEmpty(v5) ? (decimal)Convert.ChangeType(v5, typeof(decimal)) : default(decimal),
            Salesytd = dict.TryGetValue("salesytd", out var v6) && !string.IsNullOrEmpty(v6) ? (decimal)Convert.ChangeType(v6, typeof(decimal)) : default(decimal),
            Saleslastyear = dict.TryGetValue("saleslastyear", out var v7) && !string.IsNullOrEmpty(v7) ? (decimal)Convert.ChangeType(v7, typeof(decimal)) : default(decimal),
            Rowguid = dict.TryGetValue("rowguid", out var v8) && !string.IsNullOrEmpty(v8) ? (Guid)Convert.ChangeType(v8, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v9) && !string.IsNullOrEmpty(v9) ? (DateTime)Convert.ChangeType(v9, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalesperson entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "businessentityid", Value = new Value { StringValue = entity.Businessentityid.ToString() } });

        // For Postgres, add all non-primary key columns
        if (entity.Territoryid != null)
        {
            row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = entity.Territoryid.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = null } });
        }
        if (entity.Salesquota != null)
        {
            row.Entries.Add(new RowEntry { Column = "salesquota", Value = new Value { StringValue = entity.Salesquota.ToString() } });
        }
        else
        {
            row.Entries.Add(new RowEntry { Column = "salesquota", Value = new Value { StringValue = null } });
        }
        row.Entries.Add(new RowEntry { Column = "bonus", Value = new Value { StringValue = entity.Bonus.ToString() } });
        row.Entries.Add(new RowEntry { Column = "commissionpct", Value = new Value { StringValue = entity.Commissionpct.ToString() } });
        row.Entries.Add(new RowEntry { Column = "salesytd", Value = new Value { StringValue = entity.Salesytd.ToString() } });
        row.Entries.Add(new RowEntry { Column = "saleslastyear", Value = new Value { StringValue = entity.Saleslastyear.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
