using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[salesterritory] generated by the
// redfly PostgresGrpcPolyLangCompiler
// This is only meant to be indicative of the features available in the core product.

public class SalesSalesterritory : BasePostgresTableSchema
{
    public int Territoryid { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Countryregioncode { get; set; } = string.Empty;
    public string Group { get; set; } = string.Empty;
    public decimal Salesytd { get; set; }
    public decimal Saleslastyear { get; set; }
    public decimal Costytd { get; set; }
    public decimal Costlastyear { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesSalesterritoryRowsData : BaseTableRowsData
{
    public List<SalesSalesterritory> Rows { get; set; } = new();
}

public class SalesSalesterritoryInsertedData : BaseTableInsertedData
{
    public SalesSalesterritory? InsertedRow { get; set; }
}

public class SalesSalesterritoryRowData : BaseTableRowData
{
    public SalesSalesterritory? Row { get; set; }
}

public class SalesSalesterritoryDataSource : BasePostgresTableDataSource<SalesSalesterritory>
{
    public SalesSalesterritoryDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("salesterritory");
    }

    public async Task<DeletedData> DeleteAsync(int territoryid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("territoryid", territoryid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesSalesterritoryRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesSalesterritory>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesSalesterritoryRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesterritoryInsertedData> InsertAsync(SalesSalesterritory entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesterritoryInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesSalesterritoryRowData> GetAsync(int territoryid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("territoryid", territoryid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesSalesterritoryRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesSalesterritory entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesSalesterritory MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesSalesterritory
        {
            Territoryid = dict.TryGetValue("territoryid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Name = dict.TryGetValue("name", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Countryregioncode = dict.TryGetValue("countryregioncode", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Group = dict.TryGetValue("group", out var v4) && !string.IsNullOrEmpty(v4) ? (string)Convert.ChangeType(v4, typeof(string)) : default(string),
            Salesytd = dict.TryGetValue("salesytd", out var v5) && !string.IsNullOrEmpty(v5) ? (decimal)Convert.ChangeType(v5, typeof(decimal)) : default(decimal),
            Saleslastyear = dict.TryGetValue("saleslastyear", out var v6) && !string.IsNullOrEmpty(v6) ? (decimal)Convert.ChangeType(v6, typeof(decimal)) : default(decimal),
            Costytd = dict.TryGetValue("costytd", out var v7) && !string.IsNullOrEmpty(v7) ? (decimal)Convert.ChangeType(v7, typeof(decimal)) : default(decimal),
            Costlastyear = dict.TryGetValue("costlastyear", out var v8) && !string.IsNullOrEmpty(v8) ? (decimal)Convert.ChangeType(v8, typeof(decimal)) : default(decimal),
            Rowguid = dict.TryGetValue("rowguid", out var v9) && !string.IsNullOrEmpty(v9) ? (Guid)Convert.ChangeType(v9, typeof(Guid)) : default(Guid),
            Modifieddate = dict.TryGetValue("modifieddate", out var v10) && !string.IsNullOrEmpty(v10) ? (DateTime)Convert.ChangeType(v10, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesSalesterritory entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "territoryid", Value = new Value { StringValue = entity.Territoryid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "countryregioncode", Value = new Value { StringValue = entity.Countryregioncode } });
        row.Entries.Add(new RowEntry { Column = "group", Value = new Value { StringValue = entity.Group } });
        row.Entries.Add(new RowEntry { Column = "salesytd", Value = new Value { StringValue = entity.Salesytd.ToString() } });
        row.Entries.Add(new RowEntry { Column = "saleslastyear", Value = new Value { StringValue = entity.Saleslastyear.ToString() } });
        row.Entries.Add(new RowEntry { Column = "costytd", Value = new Value { StringValue = entity.Costytd.ToString() } });
        row.Entries.Add(new RowEntry { Column = "costlastyear", Value = new Value { StringValue = entity.Costlastyear.ToString() } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
