using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace redflyGeneratedDataAccessApi.Postgres.AdventureWorks;

// Strongly-typed classes for [sales].[creditcard] generated by the
// redfly PostgresGrpcPolyLangCompiler on 06/06/25 04:28:19 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesCreditcard : BasePostgresTableSchema
{
    public int Creditcardid { get; set; }
    public string Cardtype { get; set; } = string.Empty;
    public string Cardnumber { get; set; } = string.Empty;
    public short Expmonth { get; set; }
    public short Expyear { get; set; }
    public DateTime Modifieddate { get; set; }
}

public class SalesCreditcardRowsData : BaseTableRowsData
{
    public List<SalesCreditcard> Rows { get; set; } = new();
}

public class SalesCreditcardInsertedData : BaseTableInsertedData
{
    public SalesCreditcard? InsertedRow { get; set; }
}

public class SalesCreditcardRowData : BaseTableRowData
{
    public SalesCreditcard? Row { get; set; }
}

public class SalesCreditcardDataSource : BasePostgresTableDataSource<SalesCreditcard>
{
    public SalesCreditcardDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("sales");
        _encTable = RedflyEncryption.EncryptToString("creditcard");
    }

    public async Task<DeletedData> DeleteAsync(int creditcardid, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("creditcardid", creditcardid.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesCreditcardRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesCreditcard>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesCreditcardRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesCreditcardInsertedData> InsertAsync(SalesCreditcard entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesCreditcardInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesCreditcardRowData> GetAsync(int creditcardid, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("creditcardid", creditcardid.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesCreditcardRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesCreditcard entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesCreditcard MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesCreditcard
        {
            Creditcardid = dict.TryGetValue("creditcardid", out var v1) && !string.IsNullOrEmpty(v1) ? (int)Convert.ChangeType(v1, typeof(int)) : default(int),
            Cardtype = dict.TryGetValue("cardtype", out var v2) && !string.IsNullOrEmpty(v2) ? (string)Convert.ChangeType(v2, typeof(string)) : default(string),
            Cardnumber = dict.TryGetValue("cardnumber", out var v3) && !string.IsNullOrEmpty(v3) ? (string)Convert.ChangeType(v3, typeof(string)) : default(string),
            Expmonth = dict.TryGetValue("expmonth", out var v4) && !string.IsNullOrEmpty(v4) ? (short)Convert.ChangeType(v4, typeof(short)) : default(short),
            Expyear = dict.TryGetValue("expyear", out var v5) && !string.IsNullOrEmpty(v5) ? (short)Convert.ChangeType(v5, typeof(short)) : default(short),
            Modifieddate = dict.TryGetValue("modifieddate", out var v6) && !string.IsNullOrEmpty(v6) ? (DateTime)Convert.ChangeType(v6, typeof(DateTime)) : default(DateTime),
        };
    }

    protected override Row MapTableEntityToRow(SalesCreditcard entity, DbOperationType dbOperationType)
    {
        var row = new Row();

        row.Entries.Add(new RowEntry { Column = "creditcardid", Value = new Value { StringValue = entity.Creditcardid.ToString() } });

        // For Postgres, add all non-primary key columns
        row.Entries.Add(new RowEntry { Column = "cardtype", Value = new Value { StringValue = entity.Cardtype } });
        row.Entries.Add(new RowEntry { Column = "cardnumber", Value = new Value { StringValue = entity.Cardnumber } });
        row.Entries.Add(new RowEntry { Column = "expmonth", Value = new Value { StringValue = entity.Expmonth.ToString() } });
        row.Entries.Add(new RowEntry { Column = "expyear", Value = new Value { StringValue = entity.Expyear.ToString() } });
        if (entity.Modifieddate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "modifieddate", Value = new Value { StringValue = entity.Modifieddate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
