using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;

namespace redflyGeneratedDataAccessApi.SqlServer.ProxyTestAdventureWorks;

// Strongly-typed classes for [SalesLT].[ProductModel] generated by the
// redfly SqlServerGrpcPolyLangCompiler on 05/24/25 10:39:40 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesLTProductModel : BaseTableEntity
{
    public int ProductModelId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? CatalogDescription { get; set; }
    public Guid Rowguid { get; set; }
    public DateTime ModifiedDate { get; set; }
}

public class SalesLTProductModelRowsData : BaseTableRowsData
{
    public List<SalesLTProductModel> Rows { get; set; } = new();
}
public class SalesLTProductModelInsertedData : BaseTableInsertedData
{
    public SalesLTProductModel? InsertedRow { get; set; }
}
public class SalesLTProductModelRowData : BaseTableRowData
{
    public SalesLTProductModel? Row { get; set; }
}

public class SalesLTProductModelDataSource : BaseTableDataSource<SalesLTProductModel>
{
    public SalesLTProductModelDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("SalesLT");
        _encTable = RedflyEncryption.EncryptToString("ProductModel");
    }

    public async Task<DeletedData> DeleteAsync(int productModelId, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("ProductModelID", productModelId.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesLTProductModelRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesLTProductModel>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesLTProductModelRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductModelInsertedData> InsertAsync(SalesLTProductModel entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductModelInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductModelRowData> GetAsync(int productModelId, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("ProductModelID", productModelId.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductModelRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesLTProductModel entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesLTProductModel MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesLTProductModel
        {
            ProductModelId = dict.TryGetValue("ProductModelID", out var v1) && int.TryParse(v1, out var i1) ? i1 : 0,
            Name = dict.TryGetValue("Name", out var v2) ? v2 ?? string.Empty : string.Empty,
            CatalogDescription = dict.TryGetValue("CatalogDescription", out var v3) ? v3 : null,
            Rowguid = dict.TryGetValue("rowguid", out var v4) && Guid.TryParse(v4, out var g4) ? g4 : Guid.Empty,
            ModifiedDate = dict.TryGetValue("ModifiedDate", out var v5) && DateTime.TryParse(v5, out var d5) ? d5 : DateTime.MinValue,
            Version = dict.TryGetValue("Version", out var vVersion) ? Convert.FromBase64String(vVersion ?? "") : Array.Empty<byte>(),
        };
    }

    protected override Row MapTableEntityToRow(SalesLTProductModel entity, DbOperationType dbOperationType)
    {
        var row = new Row();
        if (dbOperationType != DbOperationType.Insert)
        {
            row.Entries.Add(new RowEntry { Column = "ProductModelID", Value = new Value { StringValue = entity.ProductModelId.ToString() } });
        }
        row.Entries.Add(new RowEntry { Column = "Name", Value = new Value { StringValue = entity.Name } });
        row.Entries.Add(new RowEntry { Column = "CatalogDescription", Value = new Value { StringValue = entity.CatalogDescription } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.ModifiedDate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "ModifiedDate", Value = new Value { StringValue = entity.ModifiedDate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
