using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Protos.SqlServer;

namespace redflyGeneratedDataAccessApi.SqlServer.ProxyTestAdventureWorks;

// Strongly-typed classes for [SalesLT].[ProductModelProductDescription] generated by the
// redfly SqlServerGrpcPolyLangCompiler on 05/24/25 10:33:20 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesLTProductModelProductDescription : BaseTableEntity
{
    public int ProductModelId { get; set; }
    public int ProductDescriptionId { get; set; }
    public string Culture { get; set; } = string.Empty;
    public Guid Rowguid { get; set; }
    public DateTime ModifiedDate { get; set; }
}

public class SalesLTProductModelProductDescriptionRowsData : BaseTableRowsData
{
    public List<SalesLTProductModelProductDescription> Rows { get; set; } = new();
}
public class SalesLTProductModelProductDescriptionInsertedData : BaseTableInsertedData
{
    public SalesLTProductModelProductDescription? InsertedRow { get; set; }
}
public class SalesLTProductModelProductDescriptionRowData : BaseTableRowData
{
    public SalesLTProductModelProductDescription? Row { get; set; }
}

public class SalesLTProductModelProductDescriptionDataSource : BaseTableDataSource<SalesLTProductModelProductDescription>
{
    public SalesLTProductModelProductDescriptionDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("SalesLT");
        _encTable = RedflyEncryption.EncryptToString("ProductModelProductDescription");
    }

    public async Task<DeletedData> DeleteAsync(int productModelId, int productDescriptionId, string culture, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("ProductModelID", productModelId.ToString());
        req.PrimaryKeyValues.Add("ProductDescriptionID", productDescriptionId.ToString());
        req.PrimaryKeyValues.Add("Culture", culture.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesLTProductModelProductDescriptionRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesLTProductModelProductDescription>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesLTProductModelProductDescriptionRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductModelProductDescriptionInsertedData> InsertAsync(SalesLTProductModelProductDescription entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductModelProductDescriptionInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductModelProductDescriptionRowData> GetAsync(int productModelId, int productDescriptionId, string culture, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("ProductModelID", productModelId.ToString());
        req.PrimaryKeyValues.Add("ProductDescriptionID", productDescriptionId.ToString());
        req.PrimaryKeyValues.Add("Culture", culture.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductModelProductDescriptionRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesLTProductModelProductDescription entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesLTProductModelProductDescription MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesLTProductModelProductDescription
        {
            ProductModelId = dict.TryGetValue("ProductModelID", out var v1) && int.TryParse(v1, out var i1) ? i1 : 0,
            ProductDescriptionId = dict.TryGetValue("ProductDescriptionID", out var v2) && int.TryParse(v2, out var i2) ? i2 : 0,
            Culture = dict.TryGetValue("Culture", out var v3) ? v3 ?? string.Empty : string.Empty,
            Rowguid = dict.TryGetValue("rowguid", out var v4) && Guid.TryParse(v4, out var g4) ? g4 : Guid.Empty,
            ModifiedDate = dict.TryGetValue("ModifiedDate", out var v5) && DateTime.TryParse(v5, out var d5) ? d5 : DateTime.MinValue,
            Version = dict.TryGetValue("Version", out var vVersion) ? Convert.FromBase64String(vVersion ?? "") : Array.Empty<byte>(),
        };
    }

    protected override Row MapTableEntityToRow(SalesLTProductModelProductDescription entity, DbOperationType dbOperationType)
    {
        var row = new Row();
        if (dbOperationType != DbOperationType.Insert)
        {
            row.Entries.Add(new RowEntry { Column = "ProductModelID", Value = new Value { StringValue = entity.ProductModelId.ToString() } });
            row.Entries.Add(new RowEntry { Column = "ProductDescriptionID", Value = new Value { StringValue = entity.ProductDescriptionId.ToString() } });
            row.Entries.Add(new RowEntry { Column = "Culture", Value = new Value { StringValue = entity.Culture.ToString() } });
        }
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.ModifiedDate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "ModifiedDate", Value = new Value { StringValue = entity.ModifiedDate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
