using RedflyCoreFramework;
using redflyDatabaseAdapters;
using redflyGeneratedDataAccessApi.Base;
using redflyGeneratedDataAccessApi.Common;
using redflyGeneratedDataAccessApi.Protos.DatabaseApi;

namespace redflyGeneratedDataAccessApi.SqlServer.ProxyTestAdventureWorks;

// Strongly-typed classes for [SalesLT].[ProductDescription] generated by the
// redfly SqlServerGrpcPolyLangCompiler on 05/24/25 10:39:40 PM
// This is only meant to be indicative of the features available in the core product.

public class SalesLTProductDescription : BaseTableEntity
{
    public int ProductDescriptionId { get; set; }
    public string Description { get; set; } = string.Empty;
    public Guid Rowguid { get; set; }
    public DateTime ModifiedDate { get; set; }
}

public class SalesLTProductDescriptionRowsData : BaseTableRowsData
{
    public List<SalesLTProductDescription> Rows { get; set; } = new();
}
public class SalesLTProductDescriptionInsertedData : BaseTableInsertedData
{
    public SalesLTProductDescription? InsertedRow { get; set; }
}
public class SalesLTProductDescriptionRowData : BaseTableRowData
{
    public SalesLTProductDescription? Row { get; set; }
}

public class SalesLTProductDescriptionDataSource : BaseTableDataSource<SalesLTProductDescription>
{
    public SalesLTProductDescriptionDataSource() : base()
    {
        _encSchema = RedflyEncryption.EncryptToString("SalesLT");
        _encTable = RedflyEncryption.EncryptToString("ProductDescription");
    }

    public async Task<DeletedData> DeleteAsync(int productDescriptionId, bool modifyCache = true)
    {
        var req = base.CreateDeleteRequest(modifyCache);
        req.PrimaryKeyValues.Add("ProductDescriptionID", productDescriptionId.ToString());
        return await base.DeleteCoreAsync(req);
    }

    public async Task<SalesLTProductDescriptionRowsData> GetRowsAsync(int pageNo = 1, int pageSize = 50, string orderByColumnName = "", string orderBySort = "", bool useCache = true)
    {
        var req = base.CreateGetRowsRequest(pageNo, pageSize, orderByColumnName, orderBySort);
        var resp = await _client.GetRowsAsync(req, AppGrpcSession.Headers!);
        var rows = new List<SalesLTProductDescription>();
        foreach (var row in resp.Rows)
        {
            rows.Add(MapRowToTableEntity(row));
        }
        return new SalesLTProductDescriptionRowsData
        {
            Success = resp.Success,
            Rows = rows,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductDescriptionInsertedData> InsertAsync(SalesLTProductDescription entity, bool modifyCache = true)
    {
        var req = base.CreateInsertRequest(entity, modifyCache);
        var resp = await _client.InsertAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductDescriptionInsertedData
        {
            Success = resp.Success,
            InsertedRow = resp.InsertedRow != null ? MapRowToTableEntity(resp.InsertedRow) : null,
            CacheUpdated = resp.CacheUpdated,
            Message = resp.Message
        };
    }

    public async Task<SalesLTProductDescriptionRowData> GetAsync(int productDescriptionId, bool useCache = true)
    {
        var req = base.CreateGetRequest();
        req.PrimaryKeyValues.Add("ProductDescriptionID", productDescriptionId.ToString());
        var resp = await _client.GetAsync(req, AppGrpcSession.Headers!);
        return new SalesLTProductDescriptionRowData
        {
            Success = resp.Success,
            Row = resp.Row != null ? MapRowToTableEntity(resp.Row) : null,
            FromCache = resp.FromCache,
            Message = resp.Message
        };
    }

    public async Task<UpdatedData> UpdateAsync(SalesLTProductDescription entity, bool modifyCache = true)
    {
        var req = CreateUpdateRequest(entity, modifyCache);
        return await UpdateCoreAsync(req);
    }

    protected override SalesLTProductDescription MapRowToTableEntity(Row row)
    {
        var dict = new Dictionary<string, string?>();
        foreach (var entry in row.Entries)
        {
            dict[entry.Column] = entry.Value?.StringValue;
        }
        return new SalesLTProductDescription
        {
            ProductDescriptionId = dict.TryGetValue("ProductDescriptionID", out var v1) && int.TryParse(v1, out var i1) ? i1 : 0,
            Description = dict.TryGetValue("Description", out var v2) ? v2 ?? string.Empty : string.Empty,
            Rowguid = dict.TryGetValue("rowguid", out var v3) && Guid.TryParse(v3, out var g3) ? g3 : Guid.Empty,
            ModifiedDate = dict.TryGetValue("ModifiedDate", out var v4) && DateTime.TryParse(v4, out var d4) ? d4 : DateTime.MinValue,
            Version = dict.TryGetValue("Version", out var vVersion) ? Convert.FromBase64String(vVersion ?? "") : Array.Empty<byte>(),
        };
    }

    protected override Row MapTableEntityToRow(SalesLTProductDescription entity, DbOperationType dbOperationType)
    {
        var row = new Row();
        if (dbOperationType != DbOperationType.Insert)
        {
            row.Entries.Add(new RowEntry { Column = "ProductDescriptionID", Value = new Value { StringValue = entity.ProductDescriptionId.ToString() } });
        }
        row.Entries.Add(new RowEntry { Column = "Description", Value = new Value { StringValue = entity.Description } });
        row.Entries.Add(new RowEntry { Column = "rowguid", Value = new Value { StringValue = entity.Rowguid.ToString() } });
        if (entity.ModifiedDate != DateTime.MinValue)
        {
            row.Entries.Add(new RowEntry { Column = "ModifiedDate", Value = new Value { StringValue = entity.ModifiedDate.ToString("yyyy-MM-dd HH:mm:ss.fff") } });
        }
        return row;
    }
}
